$schemaver: '2.0'
repo_url: https://github.com/byu-oit/enMotion
software:
  - aliases:
    assignment_group: PHIL_WINDLEY--PJW
    ddd:
      business_domain:
      context_map_url:
      ubiquitous_language_url:
    deploy_to_cmdb: true
    developed_by_byu: true
    links:
      swagger_urls:
      system_documentation_url: https://github.com/byu-oit/enMotion
    maintained_by:
    microservice: true
    name: enMotion
    notes:
    short_description:
    stages:
      development:
        aws_account:
        hosting_location: Other
        relationships:
          depends_on:
            db_read_only:
            db_read_write:
            software:
          reverse_proxy:
          runs_on:
            blade_server:
            rack_server:
            server_cluster:
            virtual_server:
          supports:
            service:
            software:
        urls:
          physical_url:
          product_page:
          virtual_url:
    standard_change_template_id:
    tags:
      app: enMotion
      data-sensitivity: confidential
      team:
    technologies_used:
      - AWS CodeBuild
      - Handel-Codepipeline
      - AWS CodePipeline
      - Handel
      - AWS CloudFormation
    type: library
